# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: EnvoyFilter
# metadata:
#   name: custom-network-config
#   namespace: default  # as defined in meshConfig resource.
# spec:
#   configPatches:
#   - applyTo: NETWORK_FILTER  # http connection manager is a filter in Envoy
#     match:
#       # context omitted so that this applies to both sidecars and gateways
#       listener:
#         filterChain:
#           filter:
#             name: "envoy.http_connection_manager"
#     patch:
#       operation: MERGE
#       value:
#         typed_config:
#           "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
#           use_remote_address: false
#           generate_request_id: true
#           preserve_external_request_id: true
#           always_set_request_id_in_response: true
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-route-config
  namespace: default  # as defined in meshConfig resource.
spec:
  configPatches:
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: ANY
      # context omitted so that this applies to both sidecars and gateways
      route:
        destination:
          host: "*"
    patch:
      operation: MERGE
      value:
          response_headers_to_add:
          - header:
              key: x-request-id
              value: "%REQ(x-request-id)%"

